### PR TITLE
Cassie Shi

### PR DESCRIPTION
**Pull request by CassieShi00**
#30

### CODE REVIEW

**Comment by mitchphillipson** [comment]
Can you rename your PR to have your name and adding to roster.md (similar to other submissions).

**Comment by mitchphillipson** [comment]
image

You have some merge conflicts. Your job is pick from your code and mine to get the correct format. You will delete the <<<main, ===== and >>>main lines and maybe delete other things. Then click Mark as Resolved in the upper right when you're done. Be sure to not delete any names.

Also you don't need a link to your issue, just your name.

**Comment by CassieShi00** [comment]
Hi professor,
I have already change the name of my PR, but I'm not sure how to delete the <<<main, ===== and >>>main lines and other things. Should I get it done in the terminal or on github?
Best, 
Cassie

**Comment by mitchphillipson** [comment]
Just click the "Resolve conflicts" button. You can edit in that window.

**Comment by CassieShi00** [comment]
Hi professor,
Thank you so much for your instruction! I already get it done.
Best,
Cassie

**Pull request merged**
