### PR TITLE
Add David Heinritz to roster_names.md

### PR DESCRIPTION
**Pull request by DavidHeinritz**
Linking issue #12

### CODE REVIEW

**Comment by DavidHeinritz** [comment]
Linking issue #12

**Comment by mitchphillipson** [comment]
Have you handled merge conflicts in the past?

**Comment by mitchphillipson** [comment]
I think you're good here

**Comment by DavidHeinritz** [comment]
I do. We mostly used Bitbucket and Gitlab, but Github is not too far off and I was always mostly in command line or VS Code when not doing web approvals and mergers. Looks like Github has come a ways from where we were. I will look through the recording on those automated tests you run, that's pretty cool.

**Pull request merged**
