### PR TITLE
Add Zhiying Chen to md.file

### PR DESCRIPTION
**Pull request by Zhiying-Chen**
Please add Zhiying Chen to the Markdown file.

### CODE REVIEW

**Comment by Zhiying-Chen** [comment]
#21

**Comment by mitchphillipson** [comment]
image

You have some merge conflicts. Your job is pick from your code and mine to get the correct format. You will delete the <<<main, ===== and >>>main lines and maybe delete other things. Then click Mark as Resolved in the upper right when you're done. Be sure to not delete any names.

**Comment by mitchphillipson** [comment]
Don't forget to link your issue.

**Comment by mitchphillipson** [comment]
(It's issue 18)

**Comment by Zhiying-Chen** [comment]
#18

**Comment by mitchphillipson** [comment]
Perfect, you're all done

**Pull request merged**
