### PR TITLE
Update roster_names.md with Ziyi Su hwk6

### PR DESCRIPTION
**Pull request by wotgta**

### CODE REVIEW

**Comment by mitchphillipson** [comment]
Be more specific with the title. Change "my name" to your name

**Comment by wotgta** [comment]
Sorry about that!

**Comment by mitchphillipson** [comment]
This is all part of the PR process. I'll have more for you do eventually, you'll see.

**Comment by mitchphillipson** [comment]
image

You have a few merge conflicts. You'll need to resolve these without removing any names. 

Click "Resolve Conflicts" and you'll see code that looks like

```
<<< main
Your Code Here
==========
My code here
>>> main
```

Your job is pick from your code and mine to get the correct format. You will delete the `<<<main`, `=====` and `>>>main` lines and maybe delete other things. Then click `Mark as Resolved` in the upper right when you're done. Don't forget to commit your changes (you'll get a dialogue box)

**Comment by wotgta** [comment]
Thx, all done

**Pull request merged**
