### PR TITLE
Jesmyn_Update roster_names.md

### PR DESCRIPTION
**Pull request by JesmynZhang**
to fork
#16

### CODE REVIEW

**Comment by mitchphillipson** [comment]
Can you change the name of the pull request to include your name?

**Comment by mitchphillipson** [comment]
image

You have some merge conflicts. Your job is pick from your code and mine to get the correct format. You will delete the <<<main, ===== and >>>main lines and maybe delete other things. Then click Mark as Resolved in the upper right when you're done. Be sure to not delete any names.

**Comment by JesmynZhang** [comment]
I have done for the conflict. Is the result right now?

**Comment by mitchphillipson** [comment]
It looks like you've deleted some names

| Yao Peng |
| Zhiying Chen |

**Comment by JesmynZhang** [comment]
> It looks like you've deleted some names
> 
> | Yao Peng | | Zhiying Chen |

Thanks for your notice! I've added them

**Pull request merged**
