### PR TITLE
Update roster_names.md

### PR DESCRIPTION
**Pull request by YuxiLi07**
This pull request addresses issue #1 by adding my name "liyuxi" to the roster.

### CODE REVIEW

**Comment by mitchphillipson** [comment]
image

You have some merge conflicts. Your job is pick from your code and mine to get the correct format. You will delete the <<<main, ===== and >>>main lines and maybe delete other things. Then click Mark as Resolved in the upper right when you're done. Be sure to not delete any names.

**Comment by mitchphillipson** [comment]
You also didn't link the correct issue. You want to link the issue you created.

**Comment by mitchphillipson** [comment]
That's fine, it's just a demonstration. You'll see the correct names when
you click "Resolve Conflicts"

**Comment by mitchphillipson** [comment]
I set it up so *everybody* is going to need to do the same thing. It was
just easier to copy/paste the same message :)

**Comment by mitchphillipson** [comment]
Reminder that this still needs to be completed

**Comment by YuxiLi07** [comment]
This pull request addresses issue https://github.com/mitchphillipson/aae718/issues/1 by adding my name "liyuxi" to the roster.

**Comment by mitchphillipson** [comment]
You also need to delete the `<<<<main` and `>>>>main` lines.

**Comment by mitchphillipson** [comment]
Perfection 👍

**Pull request merged**
