### PR TITLE
Update roster_names_Katie Strader.md

### PR DESCRIPTION
**Pull request by klstrader**
Pull request to update name list

### CODE REVIEW

**Comment by klstrader** [comment]
Added my name

**Comment by mitchphillipson** [comment]
image

You have a large number of merge conflicts. Basically the original file changed after you changed it. To resolve these click `Resolve Conflicts` and you'll need to manually change things

<<<<<<< main

The above starts your file changes

=======

Below the equals are my file

>>>>>>> main

End of changes

You need to delete those three lines and decide what's in the new file. Don't delete any names (other than duplicates) and make the markdown table look like a markdown table.

**Comment by mitchphillipson** [comment]
And you should link your issue to this PR. Just type a # and find your issue

**Comment by klstrader** [comment]
#32

**Pull request merged**
